#pragma once

#include <string>

#include "axc/Support/SourceLocation.h"

namespace axc {

/// @brief Token kinds emitted by the lexer.
enum class TokenKind {
    EndOfFile,
    Newline,
    Identifier,
    IntegerLiteral,
    FloatLiteral,
    CharLiteral,
    StringLiteral,
    LlvmBlock,

    KwFn,
    KwLet,
    KwConst,
    KwPub,
    KwPackage,
    KwReturn,
    KwDefer,
    KwStruct,
    KwEnum,
    KwClass,
    KwImport,
    KwIf,
    KwElse,
    KwSwitch,
    KwCase,
    KwDefault,
    KwWhile,
    KwFor,
    KwDo,
    KwBreak,
    KwContinue,
    KwAs,
    KwFlags,
    KwFlag,
    KwNew,
    KwWeak,
    KwRef,
    KwUnsigned,
    KwNull,
    KwExtern,
    KwLlvm,
    KwAlign,
    KwBits,
    KwInt,
    KwVoid,
    KwStr,
    KwError,
    KwBool,
    KwTrue,
    KwFalse,
    KwI2,
    KwI8,
    KwI16,
    KwI32,
    KwI64,
    KwU8,
    KwU16,
    KwU32,
    KwU64,
    KwShort,
    KwLong,
    KwDouble,
    KwFloat,
    KwF8,
    KwF16,
    KwF32,
    KwF64,
    KwChar,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Colon,
    Semicolon,
    Dot,
    At,
    Hash,
    Question,
    QuestionDot,
    Equal,
    EqualEqual,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    AmpEqual,
    PipeEqual,
    CaretEqual,
    ShiftLeftEqual,
    ShiftRightEqual,
    Bang,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Ampersand,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    Plus,
    PlusPlus,
    Minus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    ShiftLeft,
    ShiftRight,
    Arrow,
    FatArrow,
};

/// @brief Single lexed token with original source spelling and range.
struct Token {
    TokenKind kind = TokenKind::EndOfFile;
    std::string lexeme {};
    SourceRange range {};
};

/// @brief Human-readable token name used in diagnostics and debug output.
const char* tokenKindName(TokenKind kind);

}  // namespace axc
